spring:
  profiles: 
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
eureka:
  client:
    register-with-eureka: false
server:
  port: 8762
rss:
  reader:
    url: https://hk.jobsdb.com/HK/en/Rss/JobListing?jobFunctionId=131
---
spring: 
  profiles: dev  
amazon:
  dynamodb:
    endpoint: http://localhost:33000/
    location: ap-south-1
  aws:
    accesskey: xskCMievjQcKABonsdf3nsVhe7LRdOb5OWH4ysqW
    secretkey: ENC(6mPLYf51WVS9QUP7nfcgyt50ugZx/pVI)
---
spring: 
  profiles: prod  
amazon:
  dynamodb:
    endpoint: http://localhost:33000/
    location: ap-south-1
  aws:
    accesskey: xskCMievjQcKABonsdf3nsVhe7LRdOb5OWH4ysqW
    secretkey: ENC(6mPLYf51WVS9QUP7nfcgyt50ugZx/pVI)